# -*- coding: utf-8 -*-
"""patchcore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AP7jKXHcPw7lQtt3lKu2SsRNHhkefk-D
"""

pip install anomalib torch torchvision

from anomalib.data import MVTecAD
from anomalib.models import Patchcore
from anomalib.engine import Engine


datamodule = MVTecAD(
    root="/content/drive/MyDrive/patch",
    category="carpet",
    #image_size=256,
)
datamodule.setup()

# Check train/test
print("Train samples:", len(datamodule.train_dataloader().dataset))
print("Test samples:", len(datamodule.test_dataloader().dataset))


model = Patchcore(
    backbone="resnet18",
    layers=["layer2", "layer3"],
    coreset_sampling_ratio=0.01,
)
engine = Engine(
    accelerator="cpu",
    devices=1,
    max_epochs=1,
    enable_progress_bar=False,
    logger=False,
)

engine.fit(model=model, datamodule=datamodule)

# If this works, memory exists
results = engine.test(model=model, datamodule=datamodule)
print("PatchCore inference successful")

predictions = engine.predict(model=model, datamodule=datamodule)
preds = predictions[0] # Assuming you want predictions from the first batch

print(preds.pred_score.shape)     # anomaly score per image
print(preds.anomaly_map.shape)    # pixel-level anomaly heatmap

print(results)

import matplotlib.pyplot as plt

img = preds.image[0].permute(1,2,0).cpu().numpy()
heatmap = preds.anomaly_map[0].cpu().numpy()

plt.subplot(1,2,1)
plt.title("Input Image")
plt.imshow(img)
plt.axis("off")

plt.subplot(1,2,2)
plt.title("Anomaly Map")
plt.imshow(heatmap, cmap="hot")
plt.axis("off")

plt.show()